apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: matrix-flux-modulator
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/IvayloB84/matrix-flux-modulator.git'
    targetRevision: HEAD
    path: '.'
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
