apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "code-stream-volume"
  description: "Freshly generated web application."
  annotations:
    github.com/project-slug: "IvayloB84/code-stream-volume"
    argocd/app-name: "code-stream-volume"
    backstage.io/kubernetes-label-selector: "app=code-stream-volume"
spec:
  type: service
  lifecycle: experimental
  owner: "user:default/IvayloB84"