apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "nova-core-vault"
  description: "Freshly generated web application."
  annotations:
    backstage.io/techdocs-ref: dir:.
    github.com/project-slug: "IvayloB84/nova-core-vault"
    argocd/app-name: "nova-core-vault"
    backstage.io/kubernetes-label-selector: "app=nova-core-vault"
spec:
  type: service
  lifecycle: production
  owner: "user:default/IvayloB84"