apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "edge-routing-mesh"
  description: "Freshly generated web application."
  annotations:
    backstage.io/techdocs-ref: dir:.
    github.com/project-slug: "IvayloB84/edge-routing-mesh"
    argocd/app-name: "edge-routing-mesh"
    backstage.io/kubernetes-label-selector: "app=edge-routing-mesh"
spec:
  type: service
  lifecycle: production
  owner: "user:default/IvayloB84"