apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: argocd-gitops-demo-app
  annotations:
    argocd/app-name: 'argocd-gitops-demo-app'
    backstage.io/kubernetes-label-selector: 'app=argocd-gitops-demo-app'
spec:
  type: service
  lifecycle: experimental
  owner: 'user:default/IvayloB84'