apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rails-sqlite-pvc
  namespace: default
spec:
  storageClassName: local-path  # Explicitly added to hide host paths
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi