apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-nexus-streams
  namespace: default
  labels:
    app: redis-nexus-streams
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-nexus-streams
  template:
    metadata:
      labels:
        app: redis-nexus-streams
    spec:
      containers:
        - name: app-container
          image: redis:alpine
          ports:
            - containerPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: redis-nexus-streams
  namespace: default
  labels:
    app: redis-nexus-streams
spec:
  ports:
    - port: 6379
      targetPort: 6379
  selector:
    app: redis-nexus-streams