apiVersion: apps/v1
kind: Deployment
metadata:
  name: chrono-pulse-nginx-deployment
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: chrono-pulse-nginx
  template:
    metadata:
      labels:
        app: chrono-pulse-nginx
    spec:
      containers:
        - name: app-container
          image: nginx:stable-alpine-slim
          ports:
            - containerPort: 80
          resources: {} 
