apiVersion: apps/v1
kind: Deployment
metadata:
  name: chrono-pulse-nginx
  labels:
    app: chrono-pulse-nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chrono-pulse-nginx
  template:
    metadata:
      labels:
        app: chrono-pulse-nginx
    spec:
      containers:
        - name: app-container
          image: "nginx:stable-alpine-slim"
          ports:
            - containerPort: 80
          command: ["sh","-c"]
          args: ["echo Runtime container initialized. Waiting for code deployment... && sleep infinity"]
          env:
            - name: SERVICE_TYPE
              value: "nginx"
            - name: POSTGRES_USER
              value: "postgres"
            - name: POSTGRES_PASSWORD
              value: ""
            - name: POSTGRES_DB
              value: "postgres"
            - name: REDIS_PASSWORD
              value: ""
            - name: JAVA_OPTS
              value: ""
            - name: APP_ENV
              value: ""
            - name: NGINX_ROUTING_PROFILE
              value: "standard-spa"

---
apiVersion: v1
kind: Service
metadata:
  name: chrono-pulse-nginx
  labels:
    app: chrono-pulse-nginx
spec:
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: chrono-pulse-nginx