apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rails-articles-app
  namespace: argocd
spec:
  project: default
  sources:                                                                              
    - repoURL: https://github.com/IvayloB84/ArgoCD-RootApps.git 
      targetRevision: HEAD                             
      path: argocd-apps/rails-articles-app
    - repoURL: https://github.com/IvayloB84/rails-articles-app.git
      targetRevision: HEAD
      path: rails-app-chart                                                                
  destination:
    server: https://kubernetes.default.svc
    namespace: target-production-apps
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - Replace=true
