apiVersion: v1
kind: Service
metadata:
  name: rails-app-service
  namespace: target-production-apps
  labels:
    app: rails-web
spec:
  ports:
  - port: 80
    targetPort: 3000
    name: http
    protocol: TCP
  - port: 8888
    targetPort: 8888
    name: telemetry
    protocol: TCP
  selector:
    app: rails-web
