apiVersion: apps/v1
kind: Deployment
metadata:
  name: hyper-flux-gateway-deployment
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hyper-flux-gateway
  template:
    metadata:
      labels:
        app: hyper-flux-gateway
    spec:
      containers:
        - name: app-container
          image: nginx:alpine
          ports:
            - containerPort: 80
          resources: {} 
