apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "cyber-mesh-router"
  description: "Freshly generated web application."
  annotations:
    backstage.io/techdocs-ref: dir:.
    github.com/project-slug: "IvayloB84/cyber-mesh-router"
    argocd/app-name: "cyber-mesh-router"
    backstage.io/kubernetes-label-selector: "app=cyber-mesh-router"
spec:
  type: service
  lifecycle: production
  owner: "user:default/IvayloB84"