apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "apache-media-vault"
  description: "Dynamic unprivileged Apache HTTPD server deployment verification."
  annotations:
    backstage.io/techdocs-ref: dir:.
    github.com/project-slug: "IvayloB84/apache-media-vault"
    argocd/app-name: "apache-media-vault"
    backstage.io/kubernetes-label-selector: "app=apache-media-vault"
spec:
  type: service
  lifecycle: production
  owner: "user:default/IvayloB84"