apiVersion: apps/v1
kind: Deployment
metadata:
  name: chrono-pulse-matrix-deployment
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: chrono-pulse-matrix
  template:
    metadata:
      labels:
        app: chrono-pulse-matrix
    spec:
      containers:
        - name: app-container
          image: postgres:16-alpine
          ports:
            - containerPort: 5432
          resources: {} 
