apiVersion: apps/v1
kind: Deployment
metadata:
  name: chrono-pulse-matrix
  labels:
    app: chrono-pulse-matrix
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chrono-pulse-matrix
  template:
    metadata:
      labels:
        app: chrono-pulse-matrix
    spec:
      containers:
        - name: app-container
          image: "postgres:16-alpine"
          ports:
            - containerPort: 5432
          env:
            - name: SERVICE_TYPE
              value: ""
            - name: POSTGRES_USER
              value: "postgres"
            - name: POSTGRES_PASSWORD
              value: "passwordsecret"
            - name: POSTGRES_DB
              value: "app_db"
            - name: REDIS_PASSWORD
              value: ""
            - name: JAVA_OPTS
              value: ""
            - name: APP_ENV
              value: ""
            - name: NGINX_ROUTING_PROFILE
              value: ""
---
apiVersion: v1
kind: Service
metadata:
  name: chrono-pulse-matrix
  labels:
    app: chrono-pulse-matrix
spec:
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    app: chrono-pulse-matrix