apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ""
  description: ""
  annotations:
    github.com/project-slug: "/"
    argocd/app-name: ""
    backstage.io/kubernetes-label-selector: "app="
spec:
  type: service
  lifecycle: experimental
  owner: "user:default/"