apiVersion: apps/v1
kind: Deployment
metadata:
  name: zenith-mesh-router
  labels:
    app: zenith-mesh-router
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zenith-mesh-router
  template:
    metadata:
      labels:
        app: zenith-mesh-router
    spec:
      containers:
        - name: app-container
          image: "postgres:16-alpine"
          ports:
            - containerPort: 5432
---
apiVersion: v1
kind: Service
metadata:
  name: zenith-mesh-router
  labels:
    app: zenith-mesh-router
spec:
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    app: zenith-mesh-router