apiVersion: apps/v1
kind: Deployment
metadata:
  name: vertex-flux-broker-deployment
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: vertex-flux-broker
  template:
    metadata:
      labels:
        app: vertex-flux-broker
    spec:
      containers:
        - name: app-container
          image: postgres:16-alpine
          ports:
            - containerPort: 5432
          resources: {} 
