apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "gitops-recursive-apex-v1"
  description: "Freshly generated application."
  annotations:
    github.com/project-slug: "IvayloB84/gitops-recursive-apex-v1"
    argocd/app-name: "gitops-recursive-apex-v1"
    backstage.io/kubernetes-label-selector: "app=gitops-recursive-apex-v1"
spec:
  type: service
  lifecycle: experimental
  owner: "user:default/IvayloB84"