apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "gitops-nexus-master-v5"
  description: "Freshly generated application."
  annotations:
    github.com/project-slug: "IvayloB84/gitops-nexus-master-v5"
    argocd/app-name: "gitops-nexus-master-v5"
    backstage.io/kubernetes-label-selector: "app=gitops-nexus-master-v5"
spec:
  type: service
  lifecycle: experimental
  owner: "user:default/IvayloB84"