apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-stream-mesh-v4
  namespace: default
  labels:
    app: go-stream-mesh-v4
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-stream-mesh-v4
  template:
    metadata:
      labels:
        app: go-stream-mesh-v4
    spec:
      containers:
        - name: app-container
          image: redis:alpine
          ports:
            - containerPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: go-stream-mesh-v4
  namespace: default
  labels:
    app: go-stream-mesh-v4
spec:
  ports:
    - port: 6379
      targetPort: 6379
  selector:
    app: go-stream-mesh-v4