apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "apex-ingress-gateway-v2"
  description: "Freshly generated web application."
  annotations:
    backstage.io/techdocs-ref: dir:.
    github.com/project-slug: "IvayloB84/apex-ingress-gateway-v2"
    argocd/app-name: "apex-ingress-gateway-v2"
    backstage.io/kubernetes-label-selector: "app=apex-ingress-gateway-v2"
spec:
  type: service
  lifecycle: production
  owner: "user:default/IvayloB84"