apiVersion: v1
kind: Service
metadata:
  name: "cyber-mesh-router-v2"
  labels:
    app: "cyber-mesh-router-v2"
spec:
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: "cyber-mesh-router-v2"