apiVersion: v1
kind: Service
metadata:
  name: "component-hydrator"
  labels:
    app: "component-hydrator"
spec:
  ports:
    - port: 6379
      targetPort: 6379
  selector:
    app: "component-hydrator"
