apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: redis-stellar-fix
  annotations:
    argocd/app-name: 'redis-stellar-fix'
    backstage.io/kubernetes-label-selector: 'app=redis-stellar-fix'
spec:
  type: service
  lifecycle: experimental
  owner: 'user:default/IvayloB84'