apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: apex-victory-sync-700
  description: "Freshly generated application."
  annotations:
    argocd/app-name: apex-victory-sync-700
    backstage.io/kubernetes-id: apex-victory-sync-700
spec:
  type: service
  lifecycle: production
  owner: user:default/ivaylob84

