apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: backstage-scaffolded-discoverer
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: 'https://github.com/IvayloB84/ArgoCD-RootApps'
        revision: main
        files:
          - path: "argocd-apps/*"
  template:
    metadata:
      name: '{{path.basename}}'
    spec:
      project: default
      source:
        repoURL: 'https://github.com/IvayloB84/{{path.basename}}.git'
        targetRevision: main
        path: k8s
      destination:
        server: https://kubernetes.default.svc
        namespace: default
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
