apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: backstage-automation-engine
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: 'https://github.com/IvayloB84/ArgoCD-RootApps'
        revision: main
        directories:
          - path: "argocd-apps/*" 
  syncPolicy:
    preserveResourcesOnDeletion: false
  template:
    metadata:
      name: "{{path.basename}}"
    spec:
      project: default
      source:
        repoURL: "https://github.com/IvayloB84/{{path.basename}}"
        targetRevision: main
        # Point directly to your deployment directory.
        # This allows your new test application to sync and scale to 3 replicas perfectly!
        path: "."
        directory:
          recurse: true
          exclude:
            - "argocd-app.yaml"
            - "catalog-info.yaml"
      destination:
        server: "https://kubernetes.default.svc"
        namespace: default
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - SkipDryRunOnMissingResource=true
