apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cluster-monitoring-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://prometheus-community.github.io/helm-charts'
    chart: kube-prometheus-stack
    targetRevision: 69.3.1                                        # Stable long-term release
    helm:
      values: |
        grafana:
          persistence:
            enabled: true
            storageClassName: "local-path"
            size: 2Gi
        prometheus:
          prometheusSpec:
            retention: 1d
            # CRITICAL K3S ROOTLESS FIX: Disables permission checks blocking the pod spawn
            securityContext:
              runAsUser: 0
              runAsGroup: 0
              fsGroup: 0
            storageSpec:
              volumeClaimTemplate:
                spec:
                  storageClassName: "local-path"
                  accessModes: ["ReadWriteOnce"]
                  resources:
                    requests:
                      storage: 5Gi