apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-scaffolded-node-app
  namespace: argocd
  labels:
    backstage.io/kubernetes-id: my-scaffolded-node-app
spec:
  project: default
  source:
    repoURL: https://github.com/IvayloB84/my-scaffolded-node-app.git
    targetRevision: feature/add-k8s-manifests
    path: k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
