apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: scaffolder-gitops-working
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://github.com/IvayloB84/backstage-pilot'
    targetRevision: HEAD
    path: catalog/skeleton
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

