apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: go-stream-mesh-v12
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/IvayloB84/go-stream-mesh-v12.git
    targetRevision: HEAD
    path: k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true