apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "gitops-flat-manifest-v1"
  description: "Automated microservice deployment tracking pipeline."
  annotations:
    github.com/project-slug: "IvayloB84/gitops-flat-manifest-v1"
    argocd/app-name: "gitops-flat-manifest-v1"
    backstage.io/kubernetes-label-selector: "app=gitops-flat-manifest-v1"
    
spec:
  type: service
  lifecycle: experimental
  owner: "user:default/IvayloB84"
