apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: flux-mesh-router
  description: Freshly generated application. [Request Component Deactivation](/create/templates/default/deactivate-service-pipeline?template_args[repoName]=flux-mesh-router)
  annotations:
    github.com/project-slug: "IvayloB84/flux-mesh-router"
    argocd/app-name: "flux-mesh-router"
    backstage.io/kubernetes-label-selector: "app=flux-mesh-router"
spec:
  type: service
  lifecycle: experimental
  owner: "user:default/IvayloB84"