apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "hird-party"
  description: "Freshly generated web application."
  annotations:
    github.com/project-slug: "IvayloB84/hird-party"
    argocd/app-name: "hird-party"
    backstage.io/kubernetes-label-selector: "app=hird-party"
spec:
  type: service
  lifecycle: experimental
  owner: "user:default/IvayloB84"