apiVersion: apps/v1
kind: Deployment
metadata:
  name: apex-victory-sync-900
  namespace: default
  labels:
    backstage.io/kubernetes-id: apex-victory-sync-900
spec:
  replicas: 1
  selector:
    matchLabels:
      backstage.io/kubernetes-id: apex-victory-sync-900
  template:
    metadata:
      labels:
        backstage.io/kubernetes-id: apex-victory-sync-900
    spec:
      containers:
        - name: app
          image: nginx:alpine
          ports:
            - containerPort: 80