apiVersion: v1
kind: Service
metadata:
  name: "plasma-java-engine-v1"
  labels:
    app: "plasma-java-engine-v1"
spec:
  ports:
    - port: 8957
      targetPort: 8957
  selector:
    app: "plasma-java-engine-v1"