apiVersion: v1
kind: Service
metadata:
  name: "plasma-java-engine-v1"
  labels:
    app: "plasma-java-engine-v1"
spec:
  ports:
    - port: 8245
      targetPort: 8245
  selector:
    app: "plasma-java-engine-v1"
