apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "decouple-service-matrix"
  description: "Freshly generated web application."
  annotations:
    github.com/project-slug: "IvayloB84/decouple-service-matrix"
    argocd/app-name: "decouple-service-matrix"
    backstage.io/kubernetes-label-selector: "app=decouple-service-matrix"
spec:
  type: service
  lifecycle: experimental
  owner: "user:default/IvayloB84"