apiVersion: apps/v1
kind: Deployment
metadata:
  name: solaris-stream-nginx-deployment
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: solaris-stream-nginx
  template:
    metadata:
      labels:
        app: solaris-stream-nginx
    spec:
      containers:
        - name: app-container
          image: nginx:alpine
          ports:
            - containerPort: 80
          resources: {} 
