apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: go-stream-mesh-v15
  annotations:
    argocd/app-name: go-stream-mesh-v15
    backstage.io/kubernetes-label-selector: 'app=go-stream-mesh-v15'
spec:
  type: service
  lifecycle: experimental
  owner: user:default/IvayloB84