apiVersion: apps/v1
kind: Deployment
metadata:
  name: orion-mesh-gate
  labels:
    app: orion-mesh-gate
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orion-mesh-gate
  template:
    metadata:
      labels:
        app: orion-mesh-gate
    spec:
      containers:
        - name: app-container
          image: "eclipse-temurin:21-jre"
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: orion-mesh-gate
  labels:
    app: orion-mesh-gate
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: orion-mesh-gate