apiVersion: v1
kind: Service
metadata:
  name: "plasma-java-engine"
  labels:
    app: "plasma-java-engine"
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: "plasma-java-engine"
