apiVersion: apps/v1
kind: Deployment
metadata:
  name: vortex-mesh-cache
  labels:
    app: vortex-mesh-cache
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vortex-mesh-cache
  template:
    metadata:
      labels:
        app: vortex-mesh-cache
    spec:
      containers:
        - name: app-container
          image: "redis:7-alpine"
          ports:
            - containerPort: 6379
          command: 
          args: 
          env:
            - name: SERVICE_TYPE
              value: "redis"
            - name: POSTGRES_USER
              value: "postgres"
            - name: POSTGRES_PASSWORD
              value: ""
            - name: POSTGRES_DB
              value: "postgres"
            - name: REDIS_PASSWORD
              value: "******"
            - name: JAVA_OPTS
              value: ""
            - name: APP_ENV
              value: ""
            - name: NGINX_ROUTING_PROFILE
              value: ""

---
apiVersion: v1
kind: Service
metadata:
  name: vortex-mesh-cache
  labels:
    app: vortex-mesh-cache
spec:
  ports:
    - port: 6379
      targetPort: 6379
  selector:
    app: vortex-mesh-cache