apiVersion: apps/v1
kind: Deployment
metadata:
  name: Aether-Flux-Gateway
  labels:
    app: Aether-Flux-Gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: Aether-Flux-Gateway
  template:
    metadata:
      labels:
        app: Aether-Flux-Gateway
    spec:
      containers:
        - name: app-container
          image: "eclipse-temurin:17-jre-alpine"
          ports:
            - containerPort: 8080
          command: sh,-c

          args: echo Runtime container initialized. Waiting for code deployment... && sleep infinity

          env:
            - name: SERVICE_TYPE
              value: "java"
            - name: POSTGRES_USER
              value: "postgres"
            - name: POSTGRES_PASSWORD
              value: ""
            - name: POSTGRES_DB
              value: "postgres"
            - name: REDIS_PASSWORD
              value: ""
            - name: JAVA_OPTS
              value: "-Xms512m -Xmx1024m"
            - name: APP_ENV
              value: "development"
            - name: NGINX_ROUTING_PROFILE
              value: ""

---
apiVersion: v1
kind: Service
metadata:
  name: Aether-Flux-Gateway
  labels:
    app: Aether-Flux-Gateway
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: Aether-Flux-Gateway