apiVersion: v1
kind: Service
metadata:
  name: "quantum-flux-matrix"
  labels:
    app: "quantum-flux-matrix"
spec:
  ports:
    - port: 8585
      targetPort: 8585
  selector:
    app: "quantum-flux-matrix"