apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "traditional-media-vault"
  description: "Freshly generated web application."
  annotations:
    github.com/project-slug: "IvayloB84/traditional-media-vault"
    argocd/app-name: "traditional-media-vault"
    backstage.io/kubernetes-label-selector: "app=traditional-media-vault-static"
spec:
  type: service
  lifecycle: production
  owner: "user:default/IvayloB84"