apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "plasma-java-engine"
  description: "Freshly generated application."
  annotations:
    github.com/project-slug: "IvayloB84/plasma-java-engine"
    argocd/app-name: "plasma-java-engine"
    backstage.io/kubernetes-label-selector: "app=plasma-java-engine"
spec:
  type: service
  lifecycle: experimental
  owner: "user:default/IvayloB84"