apiVersion: v1
kind: Service
metadata:
  name: "argo-live-service-httpd"
  labels:
    app: "argo-live-service-httpd"
spec:
  ports:
    - port: 9595
      targetPort: 9595
  selector:
    app: "argo-live-service-httpd"