apiVersion: v1
kind: Service
metadata:
  name: "nova-core-vault-v1"
  labels:
    app: "nova-core-vault-v1"
spec:
  ports:
    - port: 8649
      targetPort: 8649
  selector:
    app: "nova-core-vault-v1"
