apiVersion: v1
kind: Service
metadata:
  name: "nova-core-vault-v1-static-svc"
  labels:
    app: "nova-core-vault-v1-static"
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8657
      protocol: TCP
      name: http
  selector:
    app: "nova-core-vault-v1-static"
