apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-env-stable-deployment
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: postgres-env-stable
  template:
    metadata:
      labels:
        app: postgres-env-stable
    spec:
      containers:
        - name: app-container
          image: postgres:16-alpine
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_HOST_AUTH_METHOD
              value: trust
          resources:
            limits:
              cpu: 250m
              memory: 256Mi
            requests:
              cpu: 100m
              memory: 128Mi
