apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "lumina-stream-hydrator"
  description: "Freshly generated application."
  annotations:
    github.com/project-slug: "IvayloB84/lumina-stream-hydrator"
    argocd/app-name: "lumina-stream-hydrator"
    backstage.io/kubernetes-label-selector: "app=lumina-stream-hydrator"
spec:
  type: service
  lifecycle: experimental
  owner: "user:default/IvayloB84"