apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-modern-java-service-v6
  labels:
    app: my-modern-java-service-v6
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-modern-java-service-v6
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: my-modern-java-service-v6
    spec:
      securityContext:
        runAsUser: 10001
        runAsGroup: 10001
        fsGroup: 10001
      containers:
        - name: my-modern-java-service-v6
          image: ghcr.io/ivaylob84/my-modern-java-service-v6:ee39bf17eb3309bc1dcb2d47c82e8dd15c421737
          ports:
            - name: http
              containerPort: 8167
          resources:
            requests:
              cpu: "250m"
              memory: "256Mi"
            limits:
              cpu: "1000m"
              memory: "512Mi"
          startupProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8167
            periodSeconds: 5
            failureThreshold: 60
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8167
            periodSeconds: 15
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8167
            periodSeconds: 10
            failureThreshold: 3
          lifecycle:
            preStop:
              exec:
                command: ["sh", "-c", "sleep 10"]
      terminationGracePeriodSeconds: 60

