apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "static-asset-matrix-v2"
  description: "Freshly generated web application."
  annotations:
    github.com/project-slug: "IvayloB84/static-asset-matrix-v2"
    argocd/app-name: "static-asset-matrix-v2"
    backstage.io/kubernetes-label-selector: "app=static-asset-matrix-v2-static"
spec:
  type: service
  lifecycle: production
  owner: "user:default/IvayloB84"