apiVersion: apps/v1
kind: Deployment
metadata:
  name: final-lifecycle-router-deployment
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: final-lifecycle-router
  template:
    metadata:
      labels:
        app: final-lifecycle-router
    spec:
      containers:
        - name: app-container
          image: nginx:alpine
          ports:
            - containerPort: 80
          resources: {} 
