apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "Freshly generated application."
  description: "Freshly generated application."
  annotations:
    github.com/project-slug: "IvayloB84/vector-mesh-router"
    argocd/app-name: "vector-mesh-router"
    backstage.io/kubernetes-label-selector: "app=vector-mesh-router"
spec:
  type: service
  lifecycle: experimental
  owner: "user:default/IvayloB84"