apiVersion: v1
kind: Service
metadata:
  name: "edge-routing-mesh-v2"
  labels:
    app: "edge-routing-mesh-v2"
spec:
  ports:
    - port: 9090
      targetPort: 9090
  selector:
    app: "edge-routing-mesh-v2"
