apiVersion: v1
kind: Service
metadata:
  name: "traditional-media-vault-v2-static-svc"
  labels:
    app: "traditional-media-vault-v2-static"
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 9595
      protocol: TCP
      name: http
  selector:
    app: "traditional-media-vault-v2-static"
