apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: redis-nexus-streams
  annotations:
    argocd/app-name: 'redis-nexus-streams'
    backstage.io/kubernetes-label-selector: 'app=redis-nexus-streams'
spec:
  type: service
  lifecycle: experimental
  owner: 'user:default/IvayloB84'