apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: pulsar-shifter-x7
  description: Freshly generated application. [Request Component Deactivation](/create/templates/default/deactivate-service-pipeline?template_args[repoName]=pulsar-shifter-x7)
  annotations:
    github.com/project-slug: "IvayloB84/pulsar-shifter-x7"
    argocd/app-name: "pulsar-shifter-x7"
    backstage.io/kubernetes-label-selector: "app=pulsar-shifter-x7"
spec:
  type: service
  lifecycle: experimental
  owner: "user:default/IvayloB84"