apiVersion: v1
kind: Service
metadata:
  name: "stream-decouple-test"
  labels:
    app: "stream-decouple-test"
spec:
  ports:
    - port: 8383
      targetPort: 8383
  selector:
    app: "stream-decouple-test"
