apiVersion: v1
kind: Service
metadata:
  name: "decouple-service-matrix"
  labels:
    app: "decouple-service-matrix"
spec:
  ports:
    - port: 8787
      targetPort: 8787
  selector:
    app: "decouple-service-matrix"
