apiVersion: v1
kind: Service
metadata:
  name: "argo-live-service-reverse-proxy-proxy-svc"
  labels:
    app: "argo-live-service-reverse-proxy-proxy"
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 9494
      protocol: TCP
      name: http
  selector:
    app: "argo-live-service-reverse-proxy-proxy"