apiVersion: v1
kind: Service
metadata:
  name: "apex-ingress-gateway-v2-proxy-svc"
  labels:
    app: "apex-ingress-gateway-v2-proxy"
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 9090
      protocol: TCP
      name: http
  selector:
    app: "apex-ingress-gateway-v2-proxy"