apiVersion: v1
kind: Service
metadata:
  name: "edge-routing-mesh-proxy-svc"
  labels:
    app: "edge-routing-mesh-proxy"
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 9090
      protocol: TCP
      name: http
  selector:
    app: "edge-routing-mesh-proxy"