apiVersion: apps/v1
kind: Deployment
metadata:
  name: alpha-helix-nginx-deployment
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: alpha-helix-nginx
  template:
    metadata:
      labels:
        app: alpha-helix-nginx
    spec:
      containers:
        - name: app-container
          image: nginx:stable-alpine-slim
          ports:
            - containerPort: 80
          resources: {} 
