---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: rails-production-secrets
  namespace: default
spec:
  encryptedData:
    SECRET_KEY_BASE: AgBk7ZD9lnlSRZuIaHQN+e7Z8TImvOo21dJQka1bS7eLZ2eOkQhG3NZ+VQwVLYgIcDmLpVEhW5DvVoUqFL5jc6MPgUWW7cP+wCPOrosVVJE9hyTIjC2NKYIFFxGw9sL+nO71ymafoT7mZ5/9QOx7LuYjKgMaUQ7JI9OebzgITnDy6PXBCn5WX3jbv+n/igE47+9gxvQp967OIKOQHbd9zMn+PuodhRjKeIq97XSRvtYFEs8GOQ2800f6Kib0uloxjdBfi9LHIdgLI50A4umoD0wcijve/pmoPaDCUc/I0mew5NRHNutuYLO6FulEWKd1nCY6jtFRjWOeJVO8gmNr6rsgXVBSOadOaTgAjDBFXYBBN0y+fuB0mAhtgl1pcwS7L0swquJSQfY/0I61ZZlS6Ggbqwn7atttAAWxlEQx6/Q4vMYMwfjClKevpIMRA0AmzQkjpIrmLyIMloD5GIyPpbF+VznzuLJPbwFzKgBXxMEgbMK56HoqUkmxoOI5ZLoWBlWg/sPm6Ck8HP8nGfPD2fHsIBqWosjF/XltWhLMg+HSU5WOxIBFpve+uQxSm5AhKV1KG+Tu3BcOklvdMRpAuKNnS0dzHGMxDCjBnZW3cy1WFWtDBbJOknFr1tq+KSveRAaAWopnogeiFem8xpWdoi7UxxL9utJOeck1cR1YTD19g2Qs9y8xeNC9VEzTP5nEesT9uix2c5/QT/8W36mQLWrc1AWQsUeumT1/mLq3SRbCefDOfUSuMoLPSUcpLT4N/8X5U/9MjrAszI9mkTtnAdElcwka4LRWCrEkaGfy9KkLtUKL8V5H6n0tGkb46yh2vOytIJWaGMSZqxFKG2lIeHqXxzmhLQvv1NMi0Ne/8Rcxkw==
  template:
    metadata:
      name: rails-production-secrets
      namespace: default
    type: Opaque
