apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: matrix-router-v9
  description: Freshly generated application. [Request Component Deactivation](/create/templates/default/deactivate-service-pipeline?template_args[repoName]=matrix-router-v9)
  annotations:
    github.com/project-slug: "IvayloB84/matrix-router-v9"
    argocd/app-name: "matrix-router-v9"
    backstage.io/kubernetes-label-selector: "app=matrix-router-v9"
spec:
  type: service
  lifecycle: experimental
  owner: "user:default/IvayloB84"