apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: quantum-apex-vault
  description: Freshly generated application. [Request Component Deactivation](/create/templates/default/deactivate-service-pipeline?template_args[repoName]=quantum-apex-vault)
  annotations:
    github.com/project-slug: "IvayloB84/quantum-apex-vault"
    argocd/app-name: "quantum-apex-vault"
    backstage.io/kubernetes-label-selector: "app=quantum-apex-vault"
spec:
  type: service
  lifecycle: experimental
  owner: "user:default/IvayloB84"