apiVersion: v1
kind: Service
metadata:
  name: "nova-java-service"
  labels:
    app: "nova-java-service"
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: "nova-java-service"
