apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "quantum-flux-matrix"
  description: "Freshly generated web application."
  annotations:
    backstage.io/techdocs-ref: dir:.
    github.com/project-slug: "IvayloB84/quantum-flux-matrix"
    argocd/app-name: "quantum-flux-matrix"
    backstage.io/kubernetes-label-selector: "app=quantum-flux-matrix"
spec:
  type: service
  lifecycle: production
  owner: "user:default/IvayloB84"