apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "nebula-core-service"
  description: "Freshly generated application."
  annotations:
    github.com/project-slug: "IvayloB84/nebula-core-service"
    argocd/app-name: "nebula-core-service"
    backstage.io/kubernetes-label-selector: "app=nebula-core-service"
spec:
  type: service
  lifecycle: experimental
  owner: "user:default/IvayloB84"