apiVersion: apps/v1
kind: Deployment
metadata:
  name: "stratos-mesh-nginx"
  labels:
    app: "stratos-mesh-nginx"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "stratos-mesh-nginx"
  template:
    metadata:
      labels:
        app: "stratos-mesh-nginx"
    spec:
      containers:
        - name: app-container
          image: "nginx:alpine"
          ports:
            - containerPort: 80
          command: ["sh","-c"]
          args: ["echo Runtime container initialized. Waiting for code deployment... && sleep infinity"]
          resources:
            requests:
              cpu: "25m"
              memory: "16Mi"
            limits:
              cpu: "150m"
              memory: "32Mi"
          env:
            - name: SERVICE_TYPE
              value: "nginx"
            - name: POSTGRES_USER
              value: "postgres"
            - name: POSTGRES_PASSWORD
              value: ""
            - name: POSTGRES_DB
              value: "postgres"
            - name: REDIS_PASSWORD
              value: ""
            - name: JAVA_OPTS
              value: ""
            - name: APP_ENV
              value: ""
            - name: NGINX_ROUTING_PROFILE
              value: "standard-spa"