name: Rails GitOps CI/CD Pipeline

on:
  push:
    branches: [ "main" ]
    paths:
      - "rails-app/**" # Only triggers when you actually change your Ruby code!

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code files
      uses: actions/checkout@v4

    - name: Set up Docker Buildx engine
      uses: actions/setup-buildx-action@v3

    # We use a smart local cache so your gems don't re-download from scratch every push
    - name: Build local production image container
      uses: docker/build-push-action@v5
      with:
        context: ./rails-app
        file: ./rails-app/Dockerfile
        tags: rails-app:latest
        outputs: type=docker,dest=/tmp/rails-app.tar

    - name: CI Verification Complete
      run: echo "Rails build successful! Ready for cluster local loading."
# Cache Bust 1783541994
