name: Rails GitOps CI/CD Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code files
      uses: actions/checkout@v4

    - name: Set up Docker Buildx engine
      uses: docker/setup-buildx-action@v3

    - name: Authenticate with Docker Hub Engine
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Compile and Push Rails Production Docker Image
      uses: docker/build-push-action@v5
      with:
        context: ./rails-app
        file: ./rails-app/Dockerfile
        push: true
        tags: ivaylob84/rails-gallery:latest
        # High-Speed GitHub Cache Layer Mechanics
        cache-from: type=gha
        cache-to: type=gha,mode=max
# Speed test running 1783546941
