appName: ""
repoURL: "https://github.com/IvayloB84/stratus-sync-net.git"
targetRevision: "main"
path: "k8s"
# Append your custom Backstage parameters here later:
language: "" # e.g., nodeJS, python, go